# Credenciales para el envio de correos
smtp.user=tu_correo@gmail.com
smtp.pass=tu_contraseña_o_token

# Credenciales de Base de Datos Oracle
db.user=ADMIN
db.pass=HrEV$E8g1dY$Q{jc
db.name=DriveClick_high